import { Navbar } from '@/components'
import './globals.css'
import { Inter } from 'next/font/google'
import { Routes } from '@/models'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (

    <html lang="en">

      <body className={inter.className}>

        <Navbar pathnames={[Routes.HOME, Routes.CONTACTO, Routes.CATALOGO]} />

        {children}

      </body>

    </html>
  )
}
